### ISSUE TITLE
Navbar not closing fluidly on Mobile devices

### ISSUE THREAD

**Issue by bhargavmodak** [Evozone/ClassBWebSite#4]
# Description
On screens below 600px, the navbar design is changed. When the part of the navbar containing links to the other pages is made to disappear, whether, via scrolling or tapping the icon, it does not close fluidly. 

# Steps to reproduce
1. Open a device with a resolution of less than 600px width. 
OR
1. Right-click the page in a chromium environment, click inspect, change the device to a mobile device.
2. Tap the brand icon or scroll the page.

### Before closing : 
![image](https://user-images.githubusercontent.com/82528318/144198889-84544b10-fd84-4373-8e92-dad354fe1c94.png)

### After closing
![image](https://user-images.githubusercontent.com/82528318/144198935-38b07e42-60d5-4e31-baa1-3041ac98043f.png)

### After about 1 second
![image](https://user-images.githubusercontent.com/82528318/144199026-08f5c469-8be8-4eaa-bcc8-dddbe07d3b59.png)

# Possible causes
- The list is a `<ul>` element and has a style `display: table;` which might be causing some strange behavior.
- We're using `visibility: hidden;`, instead of `display: none;` on the parent navbar. This might be causing something.
  - This is unfeasible as making the parent div `display: none;` also causes the child div to not be displayed at all.
- Transitions cannot be applied to `visibility` and `display`.

**Comment by RanjeetNSuthar** [comment]
It is working perfectly with zero lag in my browser.

**Comment by bhargavmodak** [comment]
> It is working perfectly with zero lag in my browser.

Yeah, I was working on a fix; seems like it works for multiple people now.

The commit : [Make navbar toggle smoother](https://github.com/Evozone/ClassBWebSite/commit/e1f3d6ab2e0eaafcf7f2ccfd1e5c4ac81ceadee8) fixed it. 

I'll close the issue.
